### ISSUE TITLE
Andre spraak enn norsk paa Github

### ISSUE THREAD

**Issue by arockenberger** [humsamdigiforsk/organisatorisk#2]
Finne ut hvordan man kan skrive tekstfiler (i markdown) som bruker andre skriftsystemer enn det latinske med engelsk alfabet.

**Comment by naomimag** [comment]
Status:
Har tatt kontakt med Naoe som jobbet i DSC som jobber nå i USIT. Dette var faktisk kjemt problem med henne mens hun jobbet i DSC men hun hadde krav for japansk språk. Så brukte hun mest sin egen Mac. Det virker som flere har problem med uten å ha ordentlig løsning. Jeg fortsetter å sjekke inn i mellom. Men har ikke fått brukbar løsning. Så bruker jeg fortsett Google tools. Jeg oppdaterer fortsett vår IT via mail når jeg får nye informasjon.

**Comment by naomimag** [comment]
Jeg får nå beskjed fra Knut:
Usit har nå lagt ut Office 365 også for kontormaskiner.
Ikke sikkert at det hjelper deg, men jeg ville i det minste forsøkt. Det skader jo ikke.
Søk opp "Office 365" i software center, velg den som heter "64 bit - Large".
Siden det med språk ikke gir deg problemer på den bærbare, kan det jo hende at dette er løsningen, så vi får krysse fingrene.

Jeg skal prøve, ikke i dag. Men kanskje i morgen. Rapporterer hvordan det fikk.

**Comment by naomimag** [comment]
Har forsøkt å laste ned "Office 365" i software center, "64 bit - Large". Restarted også. Men situasjon er dessverre samme. Språkpakke er der, men jeg kan fremdeles ikke skrive... må jobbes fortsett. Naoe sjekket med USIT. Men svar er at "Ta kontakt med Huston". Det har jeg ikke gjort ennå. Kanskje nå må jeg gjøre...

**Comment by arockenberger** [comment]
Jeg lurer på om dette er noe som lar seg gjøre mye enklere på en Mac. Jeg skal undersøke det etter nyttår!

**Comment by arockenberger** [comment]
Har vi behov for å holde dette Issue åpent eller kan det lukkes @naomimag ?

**Comment by naomimag** [comment]
Hei Annika,

Det kan lukkes, synes jeg. Man kan bruke f.eks. japansk for å skrive selve innhold, har jeg forstått.

Naomi

14. okt. 2022 kl. 15:52 skrev Annika Rockenberger ***@***.***>:

﻿

Har vi behov for å holde dette Issue åpent eller kan det lukkes @naomimag<https://github.com/naomimag> ?
