### ISSUE TITLE
Trenger hjelp til å lage mappestruktur i Outlook

### ISSUE THREAD

**Issue by rasundsbak** [humsamdigiforsk/organisatorisk#20]
Jeg har problemer med for mye støy på min UiO-epost. Trenger å sette opp en mappe, slik at alt fra git og carpentry nettverket går rett i egen mailbox. Dersom noen har laget et slikt system på sin egen outlook, vær vennlig å ta kontakt med meg.

**Comment by giselatt** [comment]
Kanskje denne kan hjelpe deg?

https://www.uio.no/tjenester/it/e-post-kalender/outlook/hjelp/e-post/sortering.html[https://www.uio.no/tjenester/it/e-post-kalender/outlook/hjelp/e-post/sortering.html](url)

**Comment by Rasundsbak** [comment]
Jeg fikk bare opp en 404 feil

-----Original Message-----

**Comment by giselatt** [comment]
Hm. Det gjør ikke jeg...

**Comment by arockenberger** [comment]
Har vi en statusoppdatering for dette Issue? @Rasundsbak @giselatt
