### ISSUE TITLE
Hvorfor kan jeg ikke tildele et issue til mer enn ett gruppemedlem av gangen...?

### ISSUE THREAD

**Issue by Rasundsbak** [humsamdigiforsk/organisatorisk#23]
dette gjelder issuet "DH forum annonseres i disse nettverkene". Jeg klarte det med nr to i denne listen, som er et Draft...

**Comment by arockenberger** [comment]
Når det først har blitt omgjort til "Issue" så kan du legge til andre medlemmer som skal følge det opp.
