### ISSUE TITLE
Workshop om Pandoc for konvertering fra/til forskjellige tekstformater

### ISSUE THREAD

**Issue by arockenberger** [humsamdigiforsk/organisatorisk#5]
Installere Pandoc. Bruke pandoc for å få konvertert markdown-filer til f.eks. Word-filer, HTML-filer, eller pdf.

Lære om pandoc's egen versjon av markdown: (https://pandoc.org/MANUAL.html#pandocs-markdown)

**Comment by Rasundsbak** [comment]
Jeg har installert på min HP. Det virker ikke som at dette fungerer. Jeg kommer ikke lenger enn til installation wizard. Har forsøkt å åpne programvaren, men uten suksess. Kanskje vi kan se på dette på neste Pusletime?

**Comment by arockenberger** [comment]
Det er planer om å holde dette kurset https://programminghistorian.org/en/lessons/sustainable-authorship-in-plain-text-using-pandoc-and-markdown på DSC-days i januar 2023.

**Comment by arockenberger** [comment]
Kurset holdes 10. januar 2023, 9–12 i GSH LINKEN!
