### ISSUE TITLE
slette grener etter merge?

### ISSUE THREAD

**Issue by giselatt** [humsamdigiforsk/organisatorisk#6]
Når en gren har blitt sammenføyd (merged) med stammen, bør grenen da slettes av eieren for å gjøre det mer oversiktlig? Eller skal alt beholdes for historikkens skyld?

**Comment by arockenberger** [comment]
Godt spørsmål! Jeg synes det kommer litt an på hva som ble gjort og hvor "stor" grenen er. Er det bare noe små endringer eller oppdateringen, kan man slette grenen. Hvis man jobber f.eks. med et prosjekt over litt lengre tid og derfor tar flere "snapshots" på egen gren, er det kanskje bedre å bevare den.
Stort sett er det få kilobytes, så det er greit å la grenene stå :)

**Comment by arockenberger** [comment]
Kan dette Issue lukkes eller har vi behov for å videreføre diskusjonen? @giselatt
