### ISSUE TITLE
forarbeid til «Arbeidsgruppekontrakt»

### ISSUE THREAD

**Issue by giselatt** [humsamdigiforsk/organisatorisk#7]
Ville det være en idé å åpne ett (evt. tre?) dokumenter hvor vi kan legge inn tanker rundt de tre punktene du nevnte i mailen din tidligere i dag?

1. Gruppens felles mål

2. Gruppemedlemmenes rolle(r), dvs. hvem gjør hva, hvem har hvilken kompetanse i hvilket område, og hvor og hvordan vi er avhengig av hverandre; derfra lager vi en handlingsplan

3.  Hvordan skal vi jobbe sammen, dvs. tidsplaner, hva skal skje når frister blir ikke overholdt eller en oppgave er for stor/vanskelig/uklart etc.
4.

**Comment by arockenberger** [comment]
Høres ut som en bra idé! Kanskje vi lager til og med en egen mappe "arbeidsgruppeavtale" for det!

**Comment by arockenberger** [comment]
Jeg har laget en mappe med tre filer i: (https://github.com/humsamdigiforsk/organisatorisk/tree/main/ag-avtale) - det er bare å tilføre idéer, tanker, kommentarer.

**Comment by arockenberger** [comment]
Jeg lukker Issue!
